# Generated by Django 3.1.5 on 2021-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(max_length=100)),
                ('state_code', models.IntegerField()),
                ('state_name', models.CharField(max_length=100)),
                ('dist_code', models.IntegerField()),
                ('population_total', models.IntegerField()),
                ('population_male', models.IntegerField()),
                ('population_female', models.IntegerField()),
                ('population_total_0_6', models.IntegerField()),
                ('population_female_0_6', models.IntegerField()),
                ('literates_total', models.IntegerField()),
                ('literates_male', models.IntegerField()),
                ('literates_female', models.IntegerField()),
                ('sex_ratio', models.IntegerField()),
                ('child_sex_ratio', models.IntegerField()),
                ('effective_literacy_rate_total', models.IntegerField()),
                ('effective_literacy_rate_male', models.IntegerField()),
                ('effective_literacy_rate_female', models.IntegerField()),
                ('location', models.IntegerField()),
                ('total_graduates', models.IntegerField()),
                ('male_graduates', models.IntegerField()),
                ('female_graduates', models.IntegerField()),
            ],
        ),
    ]
