# Generated by Django 3.1.5 on 2021-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='population_male_0_6',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='population',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
