# Generated by Django 3.1.5 on 2021-05-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0002_auto_20210522_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('physicianid', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='population',
            name='state_code',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PhysicianSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('physicianid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityapp.patienttreatment')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('eventname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityapp.patienttreatment')),
            ],
        ),
    ]
